### ISSUE TITLE
Ability to turn Poll responses(For open endend questions) into cases

### ISSUE THREAD

**Issue by xkmato** [rapidpro/casepro#1]
Most of the time the answers to open ended questions can really easily be probable cases. The ability to have these show in casepro is a big user need.

**Comment by ericnewcomer** [comment]
This actually exists already. If you label a message in RapidPro, it will show up in the case tool.

**Comment by xkmato** [comment]
Yeah, I see how that can be useful but considering two things; 1) Casepro can "auto-label"(keyword matching), this takes some work off the humans and 2) very limited people can actually access the rapidpro workspace. I think it makes sense to have casepro get all the answers to open ended questions, label them and then we have partners try to figure out which of these can actually be cases. So I suggest we re-open this and discus more on how we go about it.

**Comment by ericnewcomer** [comment]
That we only act on unsolicited messages was an explicit concession made early on for performance reasons. It's not out of the realm of possibility, but it would increase the resources required for each casepro installation on rapidpro, which I'm not comfortable with.

**Comment by xkmato** [comment]
I get that, I think from a resource point of view, this can get really messy. But I am wondering if @ewheeler can pitch on this because from my last conversation with the Uganda Ureport team, who are strong potential user of casepro, this is are really major requirement. And again one of their major arguments is that the number of expected unsolicited messages is not very significant in terms of what they can act on compared to responses to open ended questions.

**Comment by rowanseymour** [comment]
Hmm. Right now the labelling task and the message views are only retrieving non-flow messages (type=INBOX). There's no way to specify with the API that you only want to messages which are responses to open ended questions, and grabbing all flow messages... we'd like to avoid that for performance reasons. Maybe the flow itself could label open-ended responses with something that casepro knows to pick up?

**Comment by xkmato** [comment]
I agree @rowanseymour if the flow can label(I am not sure if you meant 'label' - in rapidpro scope or flagging in general), but either way, I think this is a good place to start.

**Comment by ericnewcomer** [comment]
Right..

You can label something manually in RapidPro or using the Label Action within a Flow. As long as you label it with a CasePro managed label, then it should show up over there as well.

**Comment by ewheeler** [comment]
Alternatively, if you end a flow by asking an open-ended question -- and you don't add a rule for the response -- then the contact's reply will be considered type=INBOX and will be auto-labelled as appropriate by casepro

is that a correct assumption? cc @rowanseymour @ericnewcomer @xkmato

**Comment by ericnewcomer** [comment]
That's correct.

**Comment by xkmato** [comment]
My assumption is that we still want these to be mapped to a specific question/poll. If we don't add the response rule, then we will get the messages in casepro but we will lose them as poll responses.
