### ISSUE TITLE
Change anon contact identifiers to be pk based

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/casepro#108]
Currently in the case of anonymous UPartners orgs we use the last 6-digits of a contact UUID to generate an identifier to be displayed in place of their name. However this isn't guaranteed to be unique. Might be better to zero pad database ids, e.g. 00012345.

**Comment by rowanseymour** [comment]
After discussion decided this would be more confusing as then the ids would look like rapidpro anon ids.. but be different.

**Comment by ewheeler** [comment]
@rowanseymour could use something like https://github.com/zacharyvoase/humanhash ?

**Comment by rowanseymour** [comment]
Only if you handle all support tickets for _Why is this contact called high-mango-white-oregon-purple-charlie??_ :)
