### ISSUE TITLE
Automatic synchronization

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/casepro#133]
I am running the command: `python manage.py celery worker -A casepro -B`, but the automatic synchronization of the data not working, only work when I run pullmessages or pullcontacts command. What the celery command I need to execute to work correctly?

**Comment by rowanseymour** [comment]
There are 2 different celery queues that need to be processed - all the sync stuff happens in its own queue, see https://github.com/rapidpro/casepro/wiki/Developer-Guide

You should join the CasePro developers mailing list - that's the best place for questions like this: https://groups.google.com/forum/#!forum/casepro-dev

**Comment by teehamaral** [comment]
Ok. Thanks.
