### ISSUE TITLE
Organization sometimes shows up twice in the UI

### ISSUE THREAD

**Issue by miltontony** [rapidpro/casepro#140]
![image](https://cloud.githubusercontent.com/assets/623417/18056312/ac94784e-6e0b-11e6-8d13-352d7ff0a85c.png)

**Comment by rowanseymour** [comment]
This would only happen if a user got into a state where they were both 1) an org admin and 2) in a partner org. 

This was happening occasionally a while back but I thought it was fixed now. Has this happened recently?

**Comment by miltontony** [comment]
Yeah - I guess we probably setup a user as both an org admin and in a partner..

**Comment by rowanseymour** [comment]
I see you guys have some scripts for setting up testing data - if this happened via those - and not through the UI, then I'll close this.
