### ISSUE TITLE
Problems in response timing calculations

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/casepro#202]
* Only counts cases that have been re-assigned to a partner. Should count cases that have been re-assigned, or assigned at opening time to the partner, but exclude cases they assigned to themselves. See https://github.com/rapidpro/casepro/blob/e225631591041ea8cea7dd16a99d16cb1a3e84fe/casepro/statistics/signals.py#L57-L57
* Migration to calculate timings on existing data doesn't quite match signal logic - it wasn't updated to reflect this change to the signal logic https://github.com/rapidpro/casepro/pull/138/commits/e225631591041ea8cea7dd16a99d16cb1a3e84fe

**Comment by miltontony** [comment]
@rowanseymour this can be closed.
