### ISSUE TITLE
Request for Docker Image!

### ISSUE THREAD

**Issue by cromulus** [rapidpro/casepro#266]
Similar to [rapidpro-docker](https://github.com/rapidpro/rapidpro-docker)

**Comment by rowanseymour** [comment]
We don't use docker but you're welcome to put this together yourself

**Comment by smn** [comment]
fwiw rapidpro-docker was a community effort that started after one of the rapidpro conferences / meetups

**Comment by cromulus** [comment]
Praekelt Foundation's seems to fit the bill...
https://github.com/praekeltfoundation/casepro
