### ISSUE TITLE
Button overlapping checkbox options

### ISSUE THREAD

**Issue by rafaelbreno** [rapidpro/casepro#337]
At the endpoint `/partner/create` (logged in any org), at the input `Can Access` the options are being overlapped by the `Create` and `Cancel` buttons.

I've found out that it could be fixed by removing the class `form-control` from the list element:
- From `div.smartmin-form-field>ul.form-control`
- To: `div.smartmin-form-field>ul`

Overlapped(with class `form-control`):
<img class="no-click screenshot-image" src="https://image.prntscr.com/image/RXn0GP8DRrSFSGgJvvqijA.png" crossorigin="anonymous" alt="Lightshot screenshot" id="screenshot-image" image-id="10mf46t">

Not overlapped(without class `form-control`):
<img class="no-click screenshot-image" src="https://image.prntscr.com/image/NNooGqjWRpKzrpabrVuZrQ.png" crossorigin="anonymous" alt="Lightshot screenshot" id="screenshot-image" image-id="10mf6u2">

**Comment by rowanseymour** [comment]
This was fixed https://github.com/rapidpro/casepro/commit/105b46a028324e4255855e94f96c697d36456c5b#diff-a96f2667e9b590bf9d83e1565f9d69bec84415990faa822d3090a86325bf1ab1
