### ISSUE TITLE
Adding new users with weak passwords offers conflicting advice

### ISSUE THREAD

**Issue by imsickofmaps** [rapidpro/casepro#58]
One says 8 and another says 10 

![screenshot 2016-06-10 11 11 08](https://cloud.githubusercontent.com/assets/1228977/15959768/9948abaa-2efc-11e6-98f8-3b29cd146d4f.png)

**Comment by rowanseymour** [comment]
Fixed in https://github.com/rapidpro/casepro/pull/59
