### ISSUE TITLE
Partners should have group based access permisions

### ISSUE THREAD

**Issue by xkmato** [rapidpro/casepro#6]
Currently in Uganda one of the needs is put access restriction on some of the partners. Here a partners can monitor the same label but only for Ureporters in a specific group.

The whole point behind this is to have partners focus on messages from only specific regions(districts).

**Comment by xkmato** [comment]
@ewheeler @rowanseymour @ericnewcomer so I am wondering if you guys have given this any though, and do you think there is any value or do we have to look at it in another perspective?

**Comment by ewheeler** [comment]
so to clarify, in the Uganda case they might have a label `blue` and both partner orgs `Alice NGO` and `Bob NGO` both can see messages with label `blue`

BUT `Alice NGO` can only see messages that are labelled `blue` AND are from contacts in the group `Foo` -- whereas `Bob NGO` can only see messages that are labelled `blue` messages AND are from contacts in the group `Bar`

am i understanding this correctly? and to be more concrete these groups are typically grouping contacts by location/district? in other words `Alice NGO` is responsible for dealing with `blue` in `Arizona` while `Bob NGO` is responsible for dealing with `blue` in `Kansas`

**Comment by xkmato** [comment]
Thanks for throwing clarity on this @ewheeler

**Comment by rowanseymour** [comment]
This should be doable. We currently allow users to filter messages by group - my understanding is then that we would allow partner orgs to be associated with optional groups (in addition to labels) and then force filtering of messages by those groups.

**Comment by rowanseymour** [comment]
Labelling logic can now be determined by group membership, and labels determine partner access.
